"""This script has been autogenerated by `walkthrough snapshot`."""
import click

from etl.snapshot import Snapshot


@click.command()
@click.option(
    "--upload/--skip-upload",
    default=True,
    type=bool,
    help="Upload dataset to Snapshot",
)
def main(upload: bool) -> None:
    # Create new snapshot.
    snap = Snapshot("basemap/2023-01-11/grapher_basemap.topo.json")
    # Download data from source.
    snap.download_from_source()
    # Add file to DVC and upload to S3.
    snap.dvc_add(upload=upload)


if __name__ == "__main__":
    main()
